language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - .jest
install:
  - npm install -g npm@latest
  - npm install
script:
  - npm run lint
  - npm test
notifications:
  slack:
    rooms:
    - loadingplay:CQg5lsp4Hi9OdB79EZndUnOX#bug
    on_success: never
    on_failure: always
before_deploy:
  - npm run build
  - pwd && cd $TRAVIS_BUILD_DIR && pwd && cd public && ls && cd $TRAVIS_BUILD_DIR
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
